### ISSUE TITLE
Magazine ad - Boca Raton Observer.  BIGGER AND BOLDER - Deadline Aug 9

### ISSUE THREAD

**Issue by hhines** [hhines/Nathaaaaan#13]

**Comment by nnnn8** [comment]
Well obv I cant make it bigger.... :);)

**Comment by nnnn8** [comment]
Let me know if you pass it on, and what Lisias says about it.

**Comment by hhines** [comment]
He liked it!

**Comment by nnnn8** [comment]
Sweet.  The one I sent is ready.  And I haven't sent in the one to observer in the past, so whoever does can send it in.
