### ISSUE TITLE
October ADS

### ISSUE THREAD

**Issue by SusieSoDanca** [hhines/Nathaaaaan#4]

**Comment by nnnn8** [comment]
[Uploading color.png...]

**Comment by nnnn8** [comment]
What if we did something like this?  Let me know if you see the picture above...  Obviously we could use a different picture or whatever, add more stuff, but this is just the basic idea...

**Comment by nnnn8** [comment]
On the 7th, Dance Magazine and Dance Teacher are due for October issues.  Do we want to carry over the Studio one to either of those?  Or come up with something different?  I could try to get back to the tree one if we wanted to close out the Wonder with that for the last one....

**Comment by SusieSoDanca** [comment]
Remember Dance Magazine is more branded sophistication.  

Dance Teacher we should most definitely include the Studio Line image.  

My apprehension in doing the Studio Line in Dance Magazine really down to the pose.  It's a catalog shot- there's nothing exciting or technical.   Since we have a few days, what about taking the photo of Diana upside down- she's wearing a classic leotard and bring in the paint splatter.  In other words make it more sophisticated.

**Comment by nnnn8** [comment]
So take the upside down of Dina and kind of doing the same thing as the one we just did?  Im down.
